architecture:
  version: 0.3

  subtree:
  - name: System
    local:
    - name: DRAM
      class: DRAM
      attributes:
          #        width: 256
          #        block-size: 32
          #        word-bits: 8
        instances: 1
        word-bits: 8
        block-size: 64
        # bandwidth: 20.0

    subtree:
    - name: Chip
      attributes:
        technology: 40nm
      local:
          #  - name: GlobalBuffer
          #    entries: 65536
          #    instances: 1
          #    word-bits: 8
          #    block-size: 8
          #    num-ports: 2
          #    num-banks: 256
      - name: GlobalBuffer # 256KB buffer
        class: SRAM
        attributes:
            # depth: 8192 # 65536 / 8
            # width: 64 # 8 x8
            # n_banks: 256
            # word-bits: 8
          entries: 65536
          instances: 1
          word-bits: 8
          block-size: 64
          #bandwidth: 20.0
      subtree:
      - name: PE[0..15]
        local:
        - name: InputBuffer 
          class: SRAM
          attributes:
              #            depth: 512 # 4096 / 8
              #            width: 64 # 1 x 8 x 8
              #            block-size: 8
              #            word-bits: 8
              #            n_banks: 1 
            entries: 4096 
            instances: 16
            meshX: 16
            word-bits: 8
            block-size: 8
            num-ports: 2
            num-banks: 1

        - name: WeightBuffer 
          class: SRAM
          attributes:
              #            depth: 16384
              #            width: 64 # 8 x 8
              #            block-size: 8
              #            word-bits: 8
              #            n_banks: 8 
            entries: 16384
            instances: 128
            meshX: 16
            word-bits: 8
            block-size: 8
            num-ports: 1
            num-banks: 8
        - name: AccumulationBuffer 
          class: SRAM
          attributes:
              #            depth: 64
              #            width: 192 # 8 x 24
              #            instances: 128
              #            # block-size: 32
              #            word-bits: 24
              #            block-size: 1
              #            n_banks: 2 
            entries: 64
            instances: 128
            meshX: 16
            word-bits: 24
            cluster-size: 8
            network-word-bits: 16
            num-ports: 2
            num-banks: 2
        - name: Registers
          class: regfile
          attributes:
              #            depth: 8
              #            width: 512 # 64 x 8
              #            block-size: 1
              #            word-bits: 8
              #            n_banks: 8
            entries: 1
            instances: 1024
            meshX: 16
            word-bits: 8
            cluster-size: 64
            num-ports: 2
            num-banks: 8
        - name: MACC
          class: intmac
          attributes:
            instances: 1024
            datawidth: 8
            meshX : 16
            word-bits: 8


