architecture:
  version: 0.3

  subtree:
  - name: System
    local:
    - name: DRAM
      class: DRAM
      attributes:
          #        width: 256
          #        block_size: 32
          #        word-bits: 8
        instances: 1
        word-bits: 8
        block_size: 64
        # bandwidth: 20.0

    subtree:
    - name: Chip
      attributes:
        technology: 40nm
      local:
      - name: GlobalBuffer # 256KB buffer
        class: SRAM
        attributes:
          entries: 65536 
          width: 64
          depth: 1024
          meshX: 1
          instances: 1
          word-bits: 8
          # block_size: 1  #width % (word_bits * block_size) == 0
          n_rdwr_ports: 2
          n_banks: 1
      subtree:
      - name: PE[0..15]
        local:
        - name: InputBuffer 
          class: SRAM
          attributes:
            entries: 4096 
            width: 64
            depth: 64
            instances: 16
            meshX: 16
            word-bits: 8
            n_rdwr_ports: 2
            n_banks: 1
        - name: WeightBuffer 
          class: SRAM
          attributes:
            entries: 16384
            width: 64
            depth: 256 
            instances: 128
            meshX: 16
            word-bits: 8
            n_rdwr_ports: 2
            n_banks: 1
        - name: AccumulationBuffer 
          class: SRAM
          attributes:
            entries: 64
            depth: 64
            width: 24
            instances: 128
            meshX: 16
            word-bits: 24
            cluster-size: 8
            network-word-bits: 16
            n_rdwr_ports: 2
            n_banks: 1
        - name: Registers
          class: SRAM
          attributes:
            depth: 1
            width: 8
            entries: 1
            instances: 1024
            meshX: 16
            word-bits: 8
            cluster-size: 64
            n_rdwr_ports: 2
            n_banks: 1
        - name: MACC
          class: intmac
          attributes:
            instances: 1024
            datawidth: 8
            meshX: 16
            word-bits: 8


